Feature/register component
LittleCodersCrew/CodersCamp2020.Project.React.MyPlants pull request #10
Opened 2021-03-26 10:28 UTC by KonradMierzejewski

No tests yet, any ideas for them?

2021-03-26 11:14 UTC, Suegro24 approved these changes

2021-03-26 12:36 UTC, brzeczkowskaw commented
Shouldn't there be a validation for repeat password checking if it's the same?

2021-03-26 12:49 UTC, adax10 requested changes
I think there should be a message displayed which is incorrect in the validation. And the password should be at least 5 characters long, because it's like that on the server side.

2021-03-28 13:25 UTC, adax10 approved these changes

2021-03-28 13:34 UTC, kami3la approved these changes

2021-03-28 14:08 UTC, merged