Feature/auth
LittleCodersCrew/CodersCamp2020.Project.React.MyPlants pull request #15
Opened 2021-03-29 16:47 UTC by Suegro24

2021-03-29 17:31 UTC, adax10 approved these changes

2021-03-29 20:01 UTC, Nilphym requested changes

2021-03-29 20:01 UTC, Nilphym commented on src/components/useToken/useToken.js
> +  };
If this is a hook it shouldn't be in components folder but in hooks folder

2021-03-30 13:33 UTC, Nilphym approved these changes

2021-03-30 14:08 UTC, kami3la approved these changes

2021-03-31 14:45 UTC, merged