Feature/add plant
LittleCodersCrew/CodersCamp2020.Project.React.MyPlants pull request #19
Opened 2021-04-04 15:42 UTC by KonradMierzejewski

I need a little help on styling, I don't know how to style some elements (you can see it on AddPlant -> select and button components). If I missed some functionality, let me know.

2021-04-05 13:27 UTC, adax10 requested changes
And logic is missing.

2021-04-05 13:27 UTC, adax10 commented on src/containers/AddPlant/AddPlant.js
> +        <Select className={styles.select} title="Min temperature" values={[10, 15, 20]} />
Why do you enter class names for imported components? It doesn't make sense, if you want to style them appeal through children.

2021-04-05 14:01 UTC, kami3la commented
- when you import, you do not have to double-write something in the paths because we have index files to make importing easier
- instead of importing `styles`, import specific styles
- change the name of the show style to another so that it does not repeat and in the file with styles also change this name and it should work
![image](https://user-images.githubusercontent.com/72015867/113582019-26475780-9628-11eb-88aa-b410539fbea7.png)

2021-04-06 15:35 UTC, Nilphym commented
You don't have to import specific styles if it is problematic, for larger components there can be some naming issues with other variables

2021-04-13 23:40 UTC, closed without merging